# Generated by Django 4.0.3 on 2022-07-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
