# Generated by Django 4.0.3 on 2022-08-27 00:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_followers_profile_followers_followers_user_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='users.Followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
