# Generated by Django 4.0.3 on 2022-11-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_followers_profile_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default_avatar/default_avatar.png', upload_to='users_avatars'),
        ),
    ]
