# Generated by Django 4.0.3 on 2022-04-23 18:43

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_alter_tweet_quote_of_alter_tweet_reply_to_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='src',
            new_name='file',
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(default=None, max_length=50, validators=[tweets.models.validate_media_type]),
        ),
    ]
