# Generated by Django 4.0.3 on 2022-04-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0006_remove_tweet_quote_of_remove_tweet_reply_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tweets.tweet'),
        ),
    ]
