# Generated by Django 4.0.3 on 2022-06-06 23:30

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_alter_media_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='', validators=[tweets.models.validate_media_type]),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
