# Generated by Django 4.0.3 on 2022-06-06 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_alter_tweet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='related_to',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweet'),
        ),
    ]
