# Generated by Django 4.0.3 on 2022-06-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_alter_tweet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
