# Generated by Django 4.0.3 on 2022-06-22 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0016_alter_tweet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
    ]
