# Generated by Django 4.0.3 on 2022-07-18 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0017_remove_media_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
