# Generated by Django 4.0.3 on 2022-08-27 00:46

from django.db import migrations, models
import tweets.models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0018_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, validators=[tweets.models.validate_tweet_type]),
        ),
    ]
