# Generated by Django 4.0.3 on 2022-09-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0024_alter_tweet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
