# Generated by Django 4.0.3 on 2024-01-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0027_media_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='videos_thumbnails'),
        ),
    ]
