# Generated by Django 4.0.3 on 2024-03-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0030_alter_tweet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
