# Generated by Django 4.0.3 on 2024-04-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0031_alter_tweet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default_thumbnail/default_thumbnail.jpg', null=True, upload_to='videos_thumbnails'),
        ),
    ]
