# Generated by Django 4.0.3 on 2022-09-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('profile_id', 'type', 'content_type_id', 'object_id'), name='unique_notification'),
        ),
    ]
